// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseTea: typeof import('./src/components/BaseTea.vue')['default']
    Cup: typeof import('./src/components/Cup.vue')['default']
    IIconParkShop: typeof import('~icons/icon-park/shop')['default']
    IIconParkSleep: typeof import('~icons/icon-park/sleep')['default']
    ITeenyiconsShopOutline: typeof import('~icons/teenyicons/shop-outline')['default']
    ITwemojiRollingOnTheFloorLaughing: typeof import('~icons/twemoji/rolling-on-the-floor-laughing')['default']
    Tea: typeof import('./src/components/Tea.vue')['default']
    WaySwitch: typeof import('./src/components/WaySwitch.vue')['default']
  }
}

export { }
