// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseTea: typeof import('./src/components/BaseTea.vue')['default']
    Cup: typeof import('./src/components/Cup.vue')['default']
    IAkarIconsArrowBack: typeof import('~icons/akar-icons/arrow-back')['default']
    ICarbonChartBubblePacked: typeof import('~icons/carbon/chart-bubble-packed')['default']
    IFaSolidPlus: typeof import('~icons/fa-solid/plus')['default']
    IFileIconsLeaflet: typeof import('~icons/file-icons/leaflet')['default']
    IFluentCube20Regular: typeof import('~icons/fluent/cube20-regular')['default']
    IFluentLeafThree24Regular: typeof import('~icons/fluent/leaf-three24-regular')['default']
    IIconParkOutlineBubbleChart: typeof import('~icons/icon-park-outline/bubble-chart')['default']
    IIconParkOutlineCola: typeof import('~icons/icon-park-outline/cola')['default']
    IIconParkOutlineMilk: typeof import('~icons/icon-park-outline/milk')['default']
    IIconParkShop: typeof import('~icons/icon-park/shop')['default']
    IIconParkSleep: typeof import('~icons/icon-park/sleep')['default']
    IMdiDotsHexagon: typeof import('~icons/mdi/dots-hexagon')['default']
    INotoBubbleTea: typeof import('~icons/noto/bubble-tea')['default']
    ITablerCoffee: typeof import('~icons/tabler/coffee')['default']
    ITablerCup: typeof import('~icons/tabler/cup')['default']
    ITeenyiconsShopOutline: typeof import('~icons/teenyicons/shop-outline')['default']
    ITwemojiRollingOnTheFloorLaughing: typeof import('~icons/twemoji/rolling-on-the-floor-laughing')['default']
    IUilBackspace: typeof import('~icons/uil/backspace')['default']
    Tea: typeof import('./src/components/Tea.vue')['default']
    WaySwitch: typeof import('./src/components/WaySwitch.vue')['default']
  }
}

export { }
