export { default as CoconutFruit } from './CoconutFruit.vue'
export { default as Pearl } from './Pearl.vue'
export { default as Pudding } from './Pudding.vue'
export { default as Ice } from './Ice.vue'
export { default as Lemon } from './Lemon.vue'
